name: Format
on::
    push:
      paths:
        - 'public/data/**'

jobs:
    format: 
      runs-on: ubuntu-latest
      name: Lint files
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with: 
            node-version: '16'
        - run: npm commit
        - name: Lint
          run: npm run Lint
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - uses: stefanzweifel/git-auto-commit-action@v6
          with: 
            commit_message: 'style: linted files'
